### ISSUE TITLE
%statistic_mine_block% doubles the number

### ISSUE THREAD

**Issue by ghost** [PlaceholderAPI/Statistics-Expansion#13]
### Issue
The `%statistic_mine_block%` placeholder from the Statistic module reports twice the amount of mined blocks.

### Expected behaviour
The statistic will increment by one when a block is mined.

### Actual behaviour
The statistic is incremented by two.

https://i.imgur.com/K4lrCdf.png  <- Minecraft statistic page
https://i.imgur.com/rFbFce9.png <- The placeholder (the second lore line)

### How to reproduce
1. Download the Statistic eCloud module.
2. Mine a block (or check your current mined blocks in the Minecraft statistics menu)
3. Parse the %statistic_mine_block% placeholder
4. It will show double the actual amount of blocks mined.

**Comment by mathiasmupschi** [comment]
Hey, i just saw that you had the same Problem that i used to have, and it was annoying.
But i managed to solve it!


**Just download the Math Extension with the command /papi ecloud download Math
Then just devide the Number of Mined blocks by 2 like the following : %math_{statistic_mine_block}/2%  .**


And thats basicaly it. It worked out for me, though im pretty sure not many people even know that something like that is possible.
Have a great day!

**Comment by houtblok** [comment]
This issue is still present as of today with the latest version of PlaceholderAPI and Statistic. Pretty annoying for me as I use a leaderboards plugin that makes use of this placeholder, but it counts double on the leaderboards.

**Comment by Khrystyian** [comment]
This issue is still persistent.

**Comment by Dshooot** [comment]
Issue still active

**Comment by gorpnostic** [comment]
Hey! So you might want to not have decimals in the number and have it so that the number also doesn't go into half when breaking things like grass or flowers, i found a solution.

Go Into the **Placeholder's API** .config file and follow what I do.

If you have the math expansion, this is what you should have:
expansions:
  math:
    Disable-Warnings: false
    Rounding: half-top
    Decimals: 3
    Debug: false
    
Make sure to make the **decimals** say 0 and the **rounding** to none, this is what it should now look like:
expansions:
  math:
    Disable-Warnings: false
    Rounding: none
    Decimals: 0
    Debug: false

**Comment by Omarbida** [comment]
> Hey, i just saw that you had the same Problem that i used to have, and it was annoying. But i managed to solve it!
> 
> **Just download the Math Extension with the command /papi ecloud download Math Then just devide the Number of Mined blocks by 2 like the following : %math_{statistic_mine_block}/2% .**
> 
> And thats basicaly it. It worked out for me, though im pretty sure not many people even know that something like that is possible. Have a great day!

not all the blocks count 2 tho, some block behave normally (+1) so the math solution is not viable

**Comment by SkeJm** [comment]
issue still here

**Comment by TerdyTheTerd** [comment]
Still seeing this issue

**Comment by JesseCreator34** [comment]
still an issue

**Comment by Nxtyrs** [comment]
issue still here

**Comment by FoxyLoon** [comment]
issue still here

**Comment by MrSmi1ey** [comment]
The problem is still present, unfortunately.

**Comment by Kqliber** [comment]
This should now be fixed in 2.0.2 on the ecloud

**Comment by FoxyLoon** [comment]
finally! after 5 years!!! ahahahahahah
thanks for fixing this :)

**Comment by 011101001** [comment]
im still getting this bug for some blocks for example stone and not copper ore, coal ore but not chiseled stone bricks?
